spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:1212/
          predicates:
            - Path= api/v1**
    discovery:
     enable: true
  application:
    name: 'API Gateway'
server:
  port: '1111' 
